name: update

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore workdir
        id: workdir-restore
        uses: actions/cache/restore@v4
        with:
          path: ./.github/source/workdir
          key: workdir-cache

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
          cache-dependency-path: ./.github/source/package-lock.json

      - name: Install & Update
        run: |
          cd .github/source
          npm ci

          OUTPUT="$(npm run update)"
          echo "$OUTPUT"

          cd ../..
          git add .

          if ! git diff-index --quiet HEAD; then
            COMMIT_MESSAGE="$(echo "$OUTPUT" | tail -n 1)"

            git -c user.name='github-actions[bot]' \
                -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
                -c commit.gpgSign='false' \
                commit -m "$COMMIT_MESSAGE"
                
            git push

            if gh cache list --limit 8 | grep -q 'workdir-cache'; then
              echo "Cache with key 'workdir-cache' found. Deleting..."
              gh cache delete workdir-cache
            else
              echo "No cache with key 'workdir-cache' found."
            fi

            echo "changes=true" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save workdir
        id: workdir-save
        uses: actions/cache/save@v4
        if: env.changes == 'true'
        with:
          path: ./src/workdir
          key: workdir-cache
